// WordPress webpack config.
import defaultConfig from '@wordpress/scripts/config/webpack.config.js';

// Plugins.
import RemoveEmptyScriptsPlugin from 'webpack-remove-empty-scripts';
// eslint-disable-next-line import/default -- This is a default export, but the linter doesn't recognize it since it's importing from a CommonJS module.
import CopyWebpackPlugin from 'copy-webpack-plugin';

// Utilities.
import path from 'path';
import fastGlob from 'fast-glob';

const globSync = fastGlob.sync;

// Directories.
const sourceDir = './src/';

// Entry points.
const entriesObj = createEntriesObj();

// Minified files to copy.
const minFiles = globSync( `${ sourceDir }/**/*.min.js` );

// Creates entries object automatically from the source files.
function createEntriesObj() {
	const sourceFilePaths = globSync( `${ sourceDir }**/*.{js,css,sass,scss}`, {
		ignore: [ '**/modules/*.js', '**/*.min.js', '**/_*.{sass,scss}' ],
	} );
	const entries = {};

	sourceFilePaths.forEach( ( filePath ) => {
		const outputPath = path
			.relative( sourceDir, filePath ) // Gets the relative path without the sourceDir.
			.split( '.' )[ 0 ] // Removes the file extension.
			.replace( /(sass|scss)/, 'css' ); // Replaces sass/scss directories with css directories.
		const entryPath = path.resolve( process.cwd(), filePath );

		entries[ outputPath ] = entryPath;
	} );

	return entries;
}

export default {
	...defaultConfig,
	...{
		entry: entriesObj,
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			// Use this for Theme development, not for Plugin development.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			} ),
			// Copies already minified JS files to the build directory without reprocessing them.
			...( minFiles.length > 0
				? [
						new CopyWebpackPlugin( {
							patterns: globSync( `${ sourceDir }/**/*.min.js` ).map( ( filePath ) => ( {
								from: filePath,
								to: path.join( path.relative( sourceDir, filePath ) ),
								info: { minimized: true }, // Copies without running through Terser minimization
							} ) ),
						} ),
				  ]
				: [] ),
		],
	},
};
