#!/bin/bash

# Clean up after installation
REMOVE_CLONED_WP_SCRIPTS_PATCHES=true

# Initialization
INSTALL_GIT_LOCAL_REPO=true

# Dependencies
RUN_COMPOSER_INSTALL=true
RUN_NPM_INSTALL=true

# Development Configuration Files
ADD_CONFIG_COMPOSER=true
ADD_CONFIG_EDITORCONFIG=true
ADD_CONFIG_ESLINT=true
ADD_CONFIG_GITIGNORE=true
ADD_CONFIG_MARKDOWN_LINT_CLI2=true
ADD_CONFIG_MARKDOWN_LINT=true
ADD_CONFIG_PACKAGE=true
ADD_CONFIG_PHPCS=true
ADD_CONFIG_PHPSTAN=true
ADD_CONFIG_PRETTIER=true
ADD_CONFIG_PRETTIER_IGNORE=true
ADD_CONFIG_STYLELINT=true
ADD_CONFIG_VSCODE_RECOMMENDATIONS=true
ADD_CONFIG_VSCODE_SETTINGS=true
ADD_CONFIG_WEBPACK=true
ADD_PATCH_FILES=true

# Documentation Files
ADD_DOC_CHANGELOG=true
ADD_DOC_README=true
